### 데이터 전처리
#### 데이터 인코딩

In [1]:
from sklearn.preprocessing import LabelEncoder

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

#LabelEncoder를 객체로 생성한 후, fit()과 transform()으로 레이블 인코딩 수행
encoder=LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
print('인코딩 변환값:',labels)

인코딩 변환값: [0 1 4 5 3 3 2 2]


In [2]:
print('인코딩 클래스:',encoder.classes_)

인코딩 클래스: ['TV' '냉장고' '믹서' '선풍기' '전자레인지' '컴퓨터']


In [3]:
print('디코딩 원본값:',encoder.inverse_transform([4,5,2,0,1,1,3,3]))

디코딩 원본값: ['전자레인지' '컴퓨터' '믹서' 'TV' '냉장고' '냉장고' '선풍기' '선풍기']


원-핫 인코딩(One-Hot Encoding)

In [7]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items=['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']

#먼저 숫자 값으로 변환을 위해 LabelEncoder로 변환
encoder = LabelEncoder()
encoder.fit(items)
labels=encoder.transform(items)
labels=labels.reshape(-1,1)

#원-핫 인코딩을 적용
oh_encoder = OneHotEncoder()
oh_encoder.fit(labels)
oh_labels=oh_encoder.transform(labels)
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원 : ',oh_labels.shape)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]]
원-핫 인코딩 데이터 차원 :  (8, 6)


In [8]:
import pandas as pd
df= pd.DataFrame({'item':['TV','냉장고','전자레인지','컴퓨터','선풍기','선풍기','믹서','믹서']})
pd.get_dummies(df)
#get_dummies() : 숫자형 값으로 변환 안하고 바로 변환 가능하다.

item_TV  item_냉장고  item_믹서  item_선풍기  item_전자레인지  item_컴퓨터
0        1         0        0         0           0         0
1        0         1        0         0           0         0
2        0         0        0         0           1         0
3        0         0        0         0           0         1
4        0         0        0         1           0         0
5        0         0        0         1           0         0
6        0         0        1         0           0         0
7        0         0        1         0           0         0

피쳐 스케일링과 정규화

StandardScaler

In [11]:
from sklearn.datasets import load_iris
import pandas as pd
#붓꽃 데이터 세트를 로딩하고 dataframe으로 변환
iris = load_iris()
iris_data=iris.data
iris_df = pd.DataFrame(data=iris_data,columns=iris.feature_names)

print('평균 값')
print(iris_df.mean())
print('분산 값')
print(iris_df.var())

평균 값
sepal length (cm)    5.843333
sepal width (cm)     3.057333
petal length (cm)    3.758000
petal width (cm)     1.199333
dtype: float64
분산 값
sepal length (cm)    0.685694
sepal width (cm)     0.189979
petal length (cm)    3.116278
petal width (cm)     0.581006
dtype: float64


표준화

In [15]:
from sklearn.preprocessing import StandardScaler
#StandardScaler객체 생성
scaler=StandardScaler()
#StandardScaler로 data set 변환, fit()과 transform() 호출
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)

In [16]:
#transform()시 스케일 변환된 dataset가 numpy ndarray로 반환되어 dataframe으로 변환한다.
iris_df_scaled = pd.DataFrame(data=iris_scaled,columns=iris.feature_names)
print('평균 값')
print(iris_df_scaled.mean())
print('분산 값')
print(iris_df_scaled.var())

평균 값
sepal length (cm)   -1.690315e-15
sepal width (cm)    -1.842970e-15
petal length (cm)   -1.698641e-15
petal width (cm)    -1.409243e-15
dtype: float64
분산 값
sepal length (cm)    1.006711
sepal width (cm)     1.006711
petal length (cm)    1.006711
petal width (cm)     1.006711
dtype: float64


MinMaxScaler

In [18]:
from sklearn.preprocessing import MinMaxScaler
#MinMaxScaler 객체 생성
scaler=MinMaxScaler()
scaler.fit(iris_df)
iris_scaled=scaler.transform(iris_df)

#transform()시 스케일 변환된 dataset가 numpy ndarray로 반환되어 dataframe으로 변환한다.
iris_df_scaled = pd.DataFrame(data=iris_scaled,columns=iris.feature_names)
print('Min 값')
print(iris_df_scaled.min())
print('Max 값')
print(iris_df_scaled.max())

Min 값
sepal length (cm)    0.0
sepal width (cm)     0.0
petal length (cm)    0.0
petal width (cm)     0.0
dtype: float64
Max 값
sepal length (cm)    1.0
sepal width (cm)     1.0
petal length (cm)    1.0
petal width (cm)     1.0
dtype: float64


Notice scaling of train data and test data

In [20]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

#train data 0 to 10  , test data 0 to 5 -> dataset
train_array = np.arange(0,11).reshape(-1,1)
test_array = np.arange(0,6).reshape(-1,1)

In [21]:
scaler= MinMaxScaler() #feature_range 의 default값 : 0~1 변환
scaler.fit(train_array) # min 0 ,max 10 설정
train_scaled= scaler.transform(train_array) #1/10 scale로 데이터 변환 10 ->1로

print("원본 train_array 데이터 :",np.round(train_array.reshape(-1),2))
print("scale된 train_array 데이터: ",np.round(train_scaled.reshape(-1),2))

원본 train_array 데이터 : [ 0  1  2  3  4  5  6  7  8  9 10]
scale된 train_array 데이터:  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [23]:
#MinMaxScaler에 test_array를 fit()하면 min 0 max 5 설정
scaler.fit(test_array)
test_scaled =scaler.transform(test_array) #원본 5 -> 1변환

print("원본 test_array 데이터 :",np.round(test_array.reshape(-1),2))
print("scale된 test_array 데이터: ",np.round(test_scaled.reshape(-1),2))

원본 test_array 데이터 : [0 1 2 3 4 5]
scale된 test_array 데이터:  [0.  0.2 0.4 0.6 0.8 1. ]


학습 데이터와 테스트 데이터의 스케일링이 맞지 않는다.

학습 데이터와 테스트 데이터의 서로 다른 원본값이 동일한 값으로 변환된다.

In [24]:
scaler = MinMaxScaler()
scaler.fit(train_array)
train_scaled = scaler.transform(train_array)
print("원본 train_array 데이터 :",np.round(train_array.reshape(-1),2))
print("scale된 train_array 데이터: ",np.round(train_scaled.reshape(-1),2))

test_scaled = scaler.transform(test_array)
print("원본 test_array 데이터 :",np.round(test_array.reshape(-1),2))
print("scale된 test_array 데이터: ",np.round(test_scaled.reshape(-1),2))

원본 train_array 데이터 : [ 0  1  2  3  4  5  6  7  8  9 10]
scale된 train_array 데이터:  [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
원본 test_array 데이터 : [0 1 2 3 4 5]
scale된 test_array 데이터:  [0.  0.1 0.2 0.3 0.4 0.5]


이처럼 fit()을 test data에 적용하면 안되며 train data로부터 fit()이 적용된 scaler 객체를 이용해 transform()으로 변환해야 한다.